
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc491/src/DataFormats/PatCandidates/src/DataFormatsPatCandidates/a/DataFormatsPatCandidates_xr.cc_tmp
 "LCGReflex/std::pair<std::string,std::vector<float> >",
 "LCGReflex/pair<string,vector<float> >",
 "LCGReflex/edm::Wrapper<std::pair<std::string,std::vector<float> > >",
 "LCGReflex/edm::Wrapper<pair<string,vector<float> > >",
 "LCGReflex/std::vector<std::pair<std::string,std::vector<float> > >",
 "LCGReflex/vector<pair<string,vector<float> > >",
 "LCGReflex/edm::Wrapper<std::vector<std::pair<std::string,std::vector<float> > > >",
 "LCGReflex/edm::Wrapper<vector<pair<string,vector<float> > > >",
 "LCGReflex/pat::JetCorrFactors",
 "LCGReflex/std::vector<pat::JetCorrFactors>",
 "LCGReflex/vector<pat::JetCorrFactors>",
 "LCGReflex/edm::ValueMap<pat::JetCorrFactors>",
 "LCGReflex/edm::Wrapper<edm::ValueMap<pat::JetCorrFactors> >",
 "LCGReflex/pat::TauJetCorrFactors",
 "LCGReflex/std::vector<pat::TauJetCorrFactors>",
 "LCGReflex/vector<pat::TauJetCorrFactors>",
 "LCGReflex/edm::ValueMap<pat::TauJetCorrFactors>",
 "LCGReflex/edm::Wrapper<edm::ValueMap<pat::TauJetCorrFactors> >",
 "LCGReflex/StringMap",
 "LCGReflex/edm::Wrapper<StringMap>",
 "LCGReflex/pat::VertexAssociation",
 "LCGReflex/std::vector<pat::VertexAssociation>",
 "LCGReflex/vector<pat::VertexAssociation>",
 "LCGReflex/edm::ValueMap<pat::VertexAssociation>",
 "LCGReflex/edm::Wrapper<edm::ValueMap<pat::VertexAssociation> >",
 "LCGReflex/pat::EventHypothesis",
 "LCGReflex/std::vector<pat::EventHypothesis>",
 "LCGReflex/vector<pat::EventHypothesis>",
 "LCGReflex/edm::Wrapper<std::vector<pat::EventHypothesis> >",
 "LCGReflex/edm::Wrapper<vector<pat::EventHypothesis> >",
 "LCGReflex/std::pair<pat::IsolationKeys,reco::IsoDeposit>",
 "LCGReflex/pair<pat::IsolationKeys,reco::IsoDeposit>",
 "LCGReflex/std::vector<std::pair<pat::IsolationKeys,reco::IsoDeposit> >",
 "LCGReflex/vector<pair<pat::IsolationKeys,reco::IsoDeposit> >",
 "LCGReflex/pat::LookupTableRecord",
 "LCGReflex/std::vector<pat::LookupTableRecord>",
 "LCGReflex/vector<pat::LookupTableRecord>",
 "LCGReflex/edm::ValueMap<pat::LookupTableRecord>",
 "LCGReflex/edm::Wrapper<edm::ValueMap<pat::LookupTableRecord> >",
 "LCGReflex/pat::CandKinResolution",
 "LCGReflex/std::vector<pat::CandKinResolution>",
 "LCGReflex/vector<pat::CandKinResolution>",
 "LCGReflex/edm::ValueMap<pat::CandKinResolution>",
 "LCGReflex/edm::Wrapper<edm::ValueMap<pat::CandKinResolution> >",
 "LCGReflex/vid::CutFlowResult",
 "LCGReflex/edm::ValueMap<vid::CutFlowResult>",
 "LCGReflex/edm::Wrapper<vid::CutFlowResult>",
 "LCGReflex/edm::Wrapper<edm::ValueMap<vid::CutFlowResult> >",
 "LCGReflex/pat::UserHolder<vid::CutFlowResult>",
 "LCGReflex/pat::IsolationKeys",
//--End   tmp/slc6_amd64_gcc491/src/DataFormats/PatCandidates/src/DataFormatsPatCandidates/a/DataFormatsPatCandidates_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
